### ISSUE TITLE
不兼容violentmonkey

### ISSUE THREAD

**Issue by maboloshi** [twchen/zhihu-formatter#1]
非常感谢这个脚本
但是存在一点兼容性问题 violentmonkey脚本管理器不支持GM.*
 ```
 if (typeof GM !== "undefined" && !!GM.xmlHttpRequest)
  GM_xmlhttpRequest = GM.xmlHttpRequest;
```

**Comment by dejohnua** [comment]
> 非常感谢这个脚本
> 但是存在一点兼容性问题 violentmonkey脚本管理器不支持GM.*
> 
> ```
> if (typeof GM !== "undefined" && !!GM.xmlHttpRequest)
>  GM_xmlhttpRequest = GM.xmlHttpRequest;
> ```

多谢支持，现在这个问题应该解决了。

**Comment by twchen** [comment]
> 
> 
> 非常感谢这个脚本
> 但是存在一点兼容性问题 violentmonkey脚本管理器不支持GM.*
> 
> ```
> if (typeof GM !== "undefined" && !!GM.xmlHttpRequest)
>  GM_xmlhttpRequest = GM.xmlHttpRequest;
> ```

多谢支持，现在这个问题应该解决了。
