### ISSUE TITLE
没有图片的标注

### ISSUE THREAD

**Issue by LoneFireBlossom** [twchen/zhihu-formatter#4]
首先很感谢提供这样一个工具。
我使用时发现图片的标注似乎都没有剪藏到，例如这个答案：
https://www.zhihu.com/question/265524956/answer/308612586
![image](https://user-images.githubusercontent.com/50087596/63615116-29d6c800-c617-11e9-9a50-54856c4b2684.png)

**Comment by LoneFireBlossom** [comment]
另外就是个人感觉重拍后如果图片（和图片的备注）能居中就最好了。不过没有也没啥

**Comment by twchen** [comment]
多谢所给的建议。新的v0.11已保留标注并居中图片。
