### ISSUE TITLE
两个小建议（新功能方面）

### ISSUE THREAD

**Issue by LoneFireBlossom** [twchen/zhihu-formatter#5]
1、让知乎的“想法”也能重排。（这个我猜应该不麻烦）
举例：
https://www.zhihu.com/pin/1149695374125137920
https://www.zhihu.com/pin/1139558413460623360

2、显示完整链接（这个可能就麻烦，而且和这个插件主题“知乎重排”已经有些脱离了）
比如此回答里面，有一些作者直接粘贴而没有起名的链接：https://www.zhihu.com/question/264198516/answer/341999235
![image](https://user-images.githubusercontent.com/50087596/63869699-2a8ea600-c9eb-11e9-8b1d-bfd1dc217907.png)
这种链接剪藏到印象笔记里就会点不了。
当然这种链接不多，所以都自己把链接再复制粘贴一遍也没啥大不了的。

**Comment by twchen** [comment]
1. v0.12已支持重排想法。具体使用步骤请看[脚本主页](https://greasyfork.org/en/scripts/372064-%E7%9F%A5%E4%B9%8E%E9%87%8D%E6%8E%92for%E5%8D%B0%E8%B1%A1%E7%AC%94%E8%AE%B0)的说明。
2. 在链接上停留会显示可点击的完整链接啊。如下图
    ![link](https://user-images.githubusercontent.com/9403756/64018096-08696500-cb5e-11e9-95e7-ba72ebf344a4.png)

**Comment by LoneFireBlossom** [comment]
谢谢！关于第二点，在重排前和重排后，我的鼠标在链接上停留了很久也没有显示完整链接呀，是什么插件的功能吗？

**Comment by twchen** [comment]
是说用印象笔记剪藏后，在印象笔记里面看。

**Comment by LoneFireBlossom** [comment]
哦哦，原来是在印象笔记网页端有这个功能，客户端没有，明白了，谢谢！

**Comment by twchen** [comment]
原来如此，那这个问题还是跟这个脚本有关的。我在v0.13解决了这个问题，顺便把重定向链接改为直链了。

**Comment by LoneFireBlossom** [comment]
更新了一下感觉确实可以了，谢谢！
