### ISSUE TITLE
[新功能请求]知乎专栏数学公式剪藏

### ISSUE THREAD

**Issue by hikigaya58** [twchen/zhihu-formatter#6]
首先感谢作者的脚本，很好用！
剪藏带公式的专栏文章会出现公式无法识别的问题。具体来说就是知乎把公式生成为svg+xml的mime格式，但是剪藏的时候无法识别。剪藏回答没有出现这种情况，只有专栏有问题。关于这个bug也有跟印象笔记官方反应，不过你懂的，他们那速度，几个月了没见动。。。另外官方告诉我在chrome浏览器是正常的，我用的Firefox是不行（最新版本依然不行）。给个测试专栏链接：https://zhuanlan.zhihu.com/p/66319869
所以希望作者大大可以提供对这块的优化，谢谢！

**Comment by twchen** [comment]
只有Firefox+专栏的情况才有问题，真是奇怪。。。😅
最新的v1.0把svg转成png了，你试下问题解决了没

**Comment by hikigaya58** [comment]
非常感谢，问题解决了。
确实是怪bug，等官方不知道要等到什么时候😂

**Comment by LoneFireBlossom** [comment]
emmm，为啥我用这个重排之后公式的图片都挂了呢，比如1楼给的那个链接。chrome最新版。
看了一下这个issue隔了好久了，难道是我的网络有问题？

**Comment by twchen** [comment]
> 
> 
> emmm，为啥我用这个重排之后公式的图片都挂了呢，比如1楼给的那个链接。chrome最新版。
> 看了一下这个issue隔了好久了，难道是我的网络有问题？

我是用canvas把svg转为png的，现在浏览器不允许导出画在canvas上的cross origin图片，所以就挂了。最新版应该解决问题了。
