### ISSUE TITLE
脚本似乎不生效了

### ISSUE THREAD

**Issue by LoneFireBlossom** [twchen/zhihu-formatter#7]
chrome是最新版，无论专栏还是想法还是回答，网页上方都不显示那个重排按钮了，也重启过chrome重启过电脑都无效。比如：
![image](https://user-images.githubusercontent.com/50087596/75773916-caa5fd00-5d89-11ea-948a-9fc616f6ea7e.png)

另外依旧十分感谢作者的这个脚本，帮助很大，谢谢！

**Comment by twchen** [comment]
我刚试了一下是没问题的啊。你用的什么脚本管理器，tampermonkey还是violentmonkey还是其他？
不知道脚本有没有加载。你可以试试自己debug。在下面的位置加入一句代码
```js
function main() {
  // inject format button/link
  const url = window.location.href;
  if (url.includes("zhuanlan")) addBtnToNav();
  else if (url.includes("answer")) addLinkToNav(formatAnswer);
  alert("loaded"); // 加入这一行代码
```
如果有窗口弹出就说明脚本加载了。
如果加载了的话，可能是那个“重排”按键被知乎删了吧。
你可以试试把下面的1500改成更大的数
```js
setTimeout(main, 1500);
```
1500等待1.5s，你可以设成3000.

**Comment by LoneFireBlossom** [comment]
不好意思，回复晚了。
我用的是tampermonkey，添加上述代码后这样显示：
![image](https://user-images.githubusercontent.com/50087596/75994487-04b40200-5f36-11ea-9bac-959d5c6b24e3.png)
保存后刷新知乎页面显示一直加载，就是收藏夹栏下面一个进度条一直在动。

如果把时间改大，并没有什么影响。

**Comment by twchen** [comment]
你应该把`alter("loaded");`加到`else`的下一行。
一直有进度条那就应该是脚本没有加载吧。网页加载完后这个脚本才加载的。所以应该是你网络的问题。
不过你也可以试试把脚本开头的`@run-at document-idle`改成`@run-at document-end`。

**Comment by LoneFireBlossom** [comment]
没，我加到下一行也是提示这个错误

**Comment by twchen** [comment]
> 
> 
> 没，我加到下一行也是提示这个错误

```js
  function main() {
    // inject format button/link
    const url = window.location.href;
    if (url.includes("zhuanlan")) addBtnToNav();
    else if (url.includes("answer")) addLinkToNav(formatAnswer);
    else addLinkToNav(formatPin);
    alert("loaded"); // 加在这里，之前的回复说错了
```

**Comment by LoneFireBlossom** [comment]
![image](https://user-images.githubusercontent.com/50087596/76228255-71433f80-625b-11ea-870d-8d6b8c636e75.png)
是这样吗？我这样做了之后，随便打开了一个知乎问题的回答，并没有弹出任何窗口。
顺带，chrome今天似乎又有更新（还是昨天来着？），我也更新到了最新版。

**Comment by twchen** [comment]
没有弹出任何窗口的话，那脚本就没有加载了。可能是网络的问题，你试试其他网络环境下会不会出现。
还有你检查一下脚本有没有启用。如下图。
![1](https://user-images.githubusercontent.com/9403756/76305877-e9177580-6300-11ea-8efa-d2cb24a28ddc.jpg)
我在Chrome最新版80.0.3987.132测试了，没有出现类似问题。

**Comment by LoneFireBlossom** [comment]
我刚才突然想到会不会是和别的插件冲突了，试了一下果然……
https://greasyfork.org/zh-CN/scripts/24508-userscript-show-site-all-userjs
我开了上面这个脚本的情况下，知乎重排的按钮就没了，现在解决了，实在不好意思

**Comment by twchen** [comment]
我自己试了，没有冲突额。这个issue开着吧，看别人有没有这个问题。

**Comment by LoneFireBlossom** [comment]
嗯嗯
今天我发现这个插件打开，知乎重排也不受影响了……好奇怪。不知道之前什么情况，这么长时间不行。

**Comment by LoneFireBlossom** [comment]
今天又这样了，试了一下把上述的那个脚本关掉就正常了😂可能还和chrome里别的插件有关吧，共同造成的影响，这个我可就试不出来了，插件那么多😂

**Comment by LoneFireBlossom** [comment]
今天又这样了，试了一下把上述的那个脚本关掉就正常了😂可能还和chrome里别的插件有关吧，共同造成的影响，这个我可就试不出来了，插件那么多😂
