### ISSUE TITLE
Stack Exchange Formatter 失效

### ISSUE THREAD

**Issue by huwan** [twchen/zhihu-formatter#8]
Tampermonkey版本：4.10
Google Chrome 版本：Version 85.0.4183.102 (Official Build) (64-bit)
操作系统版本：macOS Big Sur 11.0 Beta (20A5364e)

问题描述：访问stack exchange系列网站时（比如[这个问题](https://tex.stackexchange.com/questions/507795/revtex-multiple-authors-with-no-affiliations-how-to-put-equal-contribution-as)）能够看到相应的标签、多选按钮，但是点了save this answer / save this Q&A之后一片空白。

尝试了进入隐私模式下屏蔽所有其它插件，问题依然存在。希望开发者有时间的话能看一下，谢谢~

**Comment by twchen** [comment]
> Tampermonkey版本：4.10
> Google Chrome 版本：Version 85.0.4183.102 (Official Build) (64-bit)
> 操作系统版本：macOS Big Sur 11.0 Beta (20A5364e)
> 
> 问题描述：访问stack exchange系列网站时（比如[这个问题](https://tex.stackexchange.com/questions/507795/revtex-multiple-authors-with-no-affiliations-how-to-put-equal-contribution-as)）能够看到相应的标签、多选按钮，但是点了save this answer / save this Q&A之后一片空白。
> 
> 尝试了进入隐私模式下屏蔽所有其它插件，问题依然存在。希望开发者有时间的话能看一下，谢谢~

我已经修复了这个问题，并且增加了一些功能比如保留评论，你可以更新试一下。注意现在checkbox在右上角。

**Comment by huwan** [comment]
谢谢，棒！
